version: '3.8'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - DATABASE_URL=file:/app/data/mydb.sqlite
    ports:
      - 4000:4000
    volumes:
      - ./data:/app/data  # This mounts the local data directory to /app/data in the container
    restart: always

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 8080:80
    depends_on:
      - server
    restart: always

  prisma:
    build:
      dockerfile: Dockerfile.prisma
      context: ./server
    environment:
      - DATABASE_URL=file:/app/data/mydb.sqlite
    ports:
      - 5555:5555
    volumes:
      - ./data:/app/data  # This mounts the local data directory to /app/data in the container

    depends_on:
      - server
    restart: always

