version: '3.8'
services:
  postgres:
    image: 'postgres:16rc1-alpine3.18'
    environment:
      - POSTGRES_PASSWORD=martin_admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:martin_admin@postgres:5432/postgres
    ports:
      - 4000:4000
    depends_on:
      - postgres
    restart: always

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 8080:80
    depends_on:
      - server
    restart: always

  prisma:
    build:
      dockerfile: Dockerfile.prisma
      context: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:martin_admin@postgres:5432/postgres
    ports:
      - 5555:5555
    depends_on:
      - server
    restart: always

volumes:
   postgres-data:
