version: '3.8'
services:
  postgres:
    image: 'postgres:16rc1-alpine3.18'
    environment:
      - POSTGRES_PASSWORD=martin_admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:martin_admin@postgres:5432/postgres
    depends_on:
      - postgres

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:80
    depends_on:
      - server

  prisma:
    build:
      dockerfile: Dockerfile.prisma
      context: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:martin_admin@postgres:5432/postgres
    depends_on:
      - server

volumes:
   postgres-data:
