FROM node:20.7.0-slim

# Required for prisma binary used  
RUN apt-get update && apt-get install -y openssl

WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install

COPY . .

CMD ["npx", "prisma", "studio", "--port", "5555"]
